Repository Kraigie/nostrum, pull requests merged in 2024-05, with the labels that each got.

#568 Change `command` to `component` in documentation
  lib/nostrum/struct/component.ex
Labels: enhancement

#569 Remove Nostrum.Api.get_token
  lib/nostrum/api.ex
Labels: enhancement

#565 Improve messages on shard resume
  lib/nostrum/shard/event.ex
Labels: enhancement

#566 Only attempt resume if the gateway says we can
  lib/nostrum/shard/event.ex
Labels: enhancement

#575 Add sample bot linked in issue #564
  guides/intro/intro.md
Labels: enhancement, docs

#567 Implement memory optimizations in user struct
  lib/nostrum/struct/user.ex
  lib/nostrum/struct/user/flags.ex
  test/nostrum/cache/user_cache_meta_test.exs
Labels: enhancement

#580 Drop session on invalid and unresumable session
  lib/nostrum/shard/event.ex
Labels: enhancement

#581 Log at INFO level when shard connection is up
  lib/nostrum/shard/session.ex
Labels: enhancement

#559 Add cheat sheets
  guides/cheat-sheets/api.cheatmd
  guides/cheat-sheets/qlc.cheatmd
  mix.exs
Labels: docs

#593 Remove Application.get_env call from Nostrum.Api.Base
  lib/nostrum/api/base.ex
  lib/nostrum/api/ratelimiter.ex
  lib/nostrum/application.ex
Labels: enhancement
